### ISSUE TITLE
Giant collect 

### ISSUE THREAD

**Issue by Allround2472** [QuantumV2/SugarySpireDemo1Decomp#1]
`if (global.collectsound == 10)
    scr_sound(sound_points)
global.collectsound = 0
global.collect += 1000
global.pizzameter += 1
instance_create(x, y, obj_10)
if (global.combo >= 1 && global.combotime < 60)
{
    global.combotime += 2
    global.combofreeze += 2
}
instance_destroy();`
for >< Obj_player
`collectvanish = 0
collectboxid = -4
in_the_void = 0
depth = -1
with (other.id)
{
    sprite_index = choose(spr_giantcollect1, spr_giantcollect2, spr_giantcollect3, spr_giantcollect4)
    image_speed = 0.35
    global.collected = 0
    global.collectsound = 0
}`
for create 
`ds_list_add(global.saveroom, id)`
for destroy
`if (collectvanish == 1 && collectboxid.activated == 1)
{
    x = xstart
    y = ystart
    instance_create((x + (sprite_width / 2)), (y + (sprite_height / 2)), obj_cloudeffect)
    repeat (3)
        instance_create(((x + (sprite_width / 2)) + random_range(-5, 5)), ((y + (sprite_height / 2)) + random_range(-5, 5)), obj_cloudeffect)
    collectvanish = 0
    in_the_void = 0
}
if (global.collectsound < 10)
    global.collectsound += 1`

**Comment by undertalemodtool** [comment]
Can't you just make a pull request?

**Comment by Allround2472** [comment]
shit uh
that was for step
`with (instance_place(x, y, obj_collectablebox))
{
    if (ds_list_find_index(global.saveroom, id) == -1 && activated == 0)
    {
        other.collectvanish = 1
        other.collectboxid = id
        other.x = -200
        other.y = -200
        in_the_void = 1
    }
}
if (ds_list_find_index(global.saveroom, id) != -1)
    instance_destroy();`
    room start

**Comment by Allround2472** [comment]
> Can't you just make a pull request?

I'm too stupid to use pull requests
also why are you here

**Comment by QuantumV2** [comment]
do a pull requests I'm not dealing with this shit
